### ISSUE TITLE
Twitter OAuth proxy error

### ISSUE THREAD

**Issue by maggialejandro** [malikov/Authenticate.me-Node-Server#1]
Hi there!

I am setting up this project in OpenShift & I'm getting this error when trying to access with twitter..

> ## Proxy Error
> 
> The proxy server received and invalid response from an upstream server.
> The proxy server could not handle the request GET /oauth/twitter.
> ##### Reason: **Error reading from remote server**
> ---
> 
> Apache/2.2.15 (Red Hat) Server at project-xxxx.rhcloud.com Port 80

The app is running correctly on the cloud and I've only changed this:

config.js

``` javascript
config.web.baseUrl = 'http://myproject-xxxx.rhcloud.com';

config.twitter.token = process.env.TWITTER_TOKEN || "";
config.twitter.consumerKey = process.env.TWITTER_CLIENT_ID || "asdasd3212312";
config.twitter.consumerSecret = process.env.TWITTER_CLIENT_SECRET || "asdasdasd123123";
config.twitter.callbackURL = config.web.baseUrl+"/oauth/callback?type=twitter";
```

I'm also setting the baseUrl on the mobile app constants.js.

you have any idea what could it be? is there any special config that i have to set on the twitter app?

Thanks in advance!

**Comment by malikov** [comment]
Hey @maggialejandro ,

I'll look into it this week end.

**Comment by malikov** [comment]
Hey @maggialejandro out of curiosity does it work when you're trying with instagram ? or register or the regular login ?

**Comment by maggialejandro** [comment]
Instagram almost works, It logs in correctly (shows the payload) but doesn't redirect to the app

is this instagram configuration ok?

> WEBSITE URL   http://ionic-xxxx.rhcloud.com
> REDIRECT URI  http://ionic-xxxx.rhcloud.com/oauth/callback?type=instagram

**Comment by malikov** [comment]
Hey @maggialejandro 

sorry for the late reply been busy lately. This is the server side code (api), it is supposed to redirect you to the payload page (oauth callback page, you should get a token as well) which is the output of the api. It doesn't redirect you to http://ionic-xxxx.rhcloud.com. There's no html on the node side I just made an api. However on your client side ([Authenticate.me-client-cordova-ionic](http://github.com/malikov/Authenticate.me-client-cordova-ionic)), you should check that you've reached the callback page see the authservice (/js/services/common/auth.js) line 146.

As for the twitter issue I wasn't able to reproduce it, all your configuration looks ok to me it should work fine. Are you still experiencing this issue ?

**Comment by maggialejandro** [comment]
Hi @malikov, I'll try again next week as I'm quite busy right now
Thanks for the reply!

**Comment by reimertz** [comment]
could this be because of you using http instead of https?

**Comment by malikov** [comment]
@reimertz I really don't know it seems to work fine with http on my end, have you experienced something similar to this before ?
